### ISSUE TITLE
Plugin only works with its own example.

### ISSUE THREAD

**Issue by romanr** [oliverpitsch/CSS-Shadow-to-Sketch-Style-Plugin#17]
Only box-shadow in example works. When I insert my own, valid box-shadow css nothing happens.

**Comment by oliverpitsch** [comment]
Hi Roman, sorry to read this. That surely is not the intended behaviour. Though I'm afraid there's little I can do, as I moved to Figma quite a while ago and am not maintaining this plugin anymore. 

Have a good day nevertheless! Oliver
